param(
    [string]$RepoRoot,
    [string[]]$EnvironmentPreset,
    [string]$SelectionName,
    [string]$Profile,
    [string[]]$Applications,
    [string[]]$DataServices,
    [string]$ValuesFile,
    [string]$DockerRegistry,
    [string]$Version,
    [string]$BundleOutputPath,
    [string]$ArchivePath,
    [string]$PromotionExtractPath,
    [string]$JobRoot = "platform",
    [string]$ServiceJobRoot = "services",
    [switch]$IncludeJenkins,
    [switch]$SkipServiceJobs,
    [string]$RepoUrl = "REPLACE_WITH_REPOSITORY_URL",
    [string]$BranchSpec = "REPLACE_WITH_BRANCH_SPEC",
    [string]$ScmCredentialsId,
    [bool]$UseLightweightCheckout = $true,
    [string]$OutputPath = "out\jenkins\seed-job-dsl.groovy"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

. (Join-Path -Path $PSScriptRoot -ChildPath "jenkins-job-common.ps1")
. (Join-Path -Path $PSScriptRoot -ChildPath "jenkins-job-dsl-common.ps1")

$root = Resolve-RepoRoot -RepoRoot $RepoRoot -DefaultRoot (Join-Path -Path $PSScriptRoot -ChildPath "..")
$jobPlanScript = Join-Path -Path $root -ChildPath "scripts\show-jenkins-job-plan.ps1"
Assert-RepoUrlSafety -Value $RepoUrl
Assert-BranchSpecSafety -Value $BranchSpec
Assert-ScmCredentialsIdSafety -Value $ScmCredentialsId
$repoUrlForDsl = if ([string]::IsNullOrWhiteSpace($RepoUrl)) { "REPLACE_WITH_REPOSITORY_URL" } else { $RepoUrl.Trim() }
$branchSpecForDsl = if ([string]::IsNullOrWhiteSpace($BranchSpec)) { "REPLACE_WITH_BRANCH_SPEC" } else { $BranchSpec.Trim() }
$scmCredentialsIdForDsl = if ([string]::IsNullOrWhiteSpace($ScmCredentialsId)) { "" } else { $ScmCredentialsId.Trim() }

$jobPlanArguments = New-JenkinsJobPlanArguments `
    -RepoRoot $root `
    -JobRoot $JobRoot `
    -ServiceJobRoot $ServiceJobRoot `
    -Format "json" `
    -EnvironmentPreset $EnvironmentPreset `
    -SelectionName $SelectionName `
    -Profile $Profile `
    -Applications $Applications `
    -DataServices $DataServices `
    -ValuesFile $ValuesFile `
    -DockerRegistry $DockerRegistry `
    -Version $Version `
    -BundleOutputPath $BundleOutputPath `
    -ArchivePath $ArchivePath `
    -PromotionExtractPath $PromotionExtractPath `
    -IncludeJenkins:$IncludeJenkins `
    -SkipServiceJobs:$SkipServiceJobs `
    -BoundParameters $PSBoundParameters

$jobPlanJson = (& $jobPlanScript @jobPlanArguments | Out-String).Trim()
if (-not $jobPlanJson) {
    throw "Jenkins job plan script did not return any JSON output."
}

$jobPlan = $jobPlanJson | ConvertFrom-Json
$selections = @($jobPlan.Selections)
$serviceJobs = @($jobPlan.ServiceJobs)

$folderDescriptions = @{}
$bundleRootPath = ([string]$jobPlan.JobRoot).Trim()
$serviceRootPath = ([string]$jobPlan.ServiceJobRoot).Trim()
if (-not $bundleRootPath) {
    throw "Jenkins job plan did not return a bundle JobRoot."
}
if (-not $serviceRootPath) {
    throw "Jenkins job plan did not return a ServiceJobRoot."
}

foreach ($folderPath in @(Get-FolderPathsFromJobPath -JobPath ($bundleRootPath + "/placeholder"))) {
    Add-UniqueFolderDescription -Map $folderDescriptions -Path $folderPath -Description "Generated Jenkins folder for reusable bundle validation, delivery, and promotion jobs."
}

foreach ($folderPath in @(Get-FolderPathsFromJobPath -JobPath ($serviceRootPath + "/placeholder"))) {
    Add-UniqueFolderDescription -Map $folderDescriptions -Path $folderPath -Description "Generated Jenkins folder for reusable service image build jobs."
}

foreach ($selection in $selections) {
    foreach ($job in @($selection.PipelineJobs)) {
        foreach ($folderPath in @(Get-FolderPathsFromJobPath -JobPath $job.Path)) {
            Add-UniqueFolderDescription -Map $folderDescriptions -Path $folderPath -Description "Generated Jenkins folder created from the reusable bundle job topology."
        }
    }

    Add-UniqueFolderDescription `
        -Map $folderDescriptions `
        -Path ([string]$selection.BundleFolderPath) `
        -Description ("Generated bundle job folder for selection '{0}' using profile '{1}'." -f $selection.Name, $selection.Profile) `
        -Replace
}

foreach ($serviceJob in $serviceJobs) {
    foreach ($folderPath in @(Get-FolderPathsFromJobPath -JobPath $serviceJob.Path)) {
        Add-UniqueFolderDescription -Map $folderDescriptions -Path $folderPath -Description "Generated Jenkins folder that groups service image pipeline jobs used by the selected bundle plans."
    }
}

$sortedFolderPaths = @(
    $folderDescriptions.Keys |
        Sort-Object @{ Expression = { ($_ -split "/").Count } }, @{ Expression = { $_ } }
)

$lines = @(
    "// Generated by scripts/export-jenkins-job-dsl.ps1.",
    "// SCM defaults are public-safe placeholders unless -RepoUrl and -BranchSpec are supplied.",
    ("// Selection count: {0}" -f $selections.Count),
    ("// Service job count: {0}" -f $serviceJobs.Count),
    "",
    ("String repoUrl = {0}" -f (ConvertTo-GroovyString -Value $repoUrlForDsl)),
    ("String branchSpec = {0}" -f (ConvertTo-GroovyString -Value $branchSpecForDsl)),
    ("String scmCredentialsId = {0}" -f (ConvertTo-GroovyString -Value $scmCredentialsIdForDsl)),
    ("boolean useLightweightCheckout = {0}" -f $UseLightweightCheckout.ToString().ToLowerInvariant()),
    "",
    "def configureGeneratedPipelineJob = { jobContext, String scriptPath, String descriptionText ->",
    "    jobContext.description(descriptionText)",
    "    jobContext.logRotator {",
    "        numToKeep(30)",
    "    }",
    "    jobContext.definition {",
    "        cpsScm {",
    "            lightweight(useLightweightCheckout)",
    "            scm {",
    "                git {",
    "                    remote {",
    "                        url(repoUrl)",
    "                        if (scmCredentialsId?.trim()) {",
    "                            credentials(scmCredentialsId)",
    "                        }",
    "                    }",
    "                    branch(branchSpec)",
    "                }",
    "            }",
    "            scriptPath(scriptPath)",
    "        }",
    "    }",
    "}",
    ""
)

foreach ($folderPath in $sortedFolderPaths) {
    $lines += ("folder({0}) {{" -f (ConvertTo-GroovyString -Value $folderPath))
    $lines += ("    description({0})" -f (ConvertTo-GroovyString -Value $folderDescriptions[$folderPath]))
    $lines += "}"
    $lines += ""
}

foreach ($selection in $selections) {
    foreach ($job in @($selection.PipelineJobs)) {
        $lines += Get-GeneratedPipelineJobDslLines `
            -Path ([string]$job.Path) `
            -Jenkinsfile ([string]$job.Jenkinsfile) `
            -DescriptionLines @(Get-BundlePipelineJobDescriptionLines -Selection $selection -Job $job)
    }
}

foreach ($serviceJob in $serviceJobs | Sort-Object Name) {
    $lines += Get-GeneratedPipelineJobDslLines `
        -Path ([string]$serviceJob.Path) `
        -Jenkinsfile ([string]$serviceJob.Jenkinsfile) `
        -DescriptionLines @(Get-ServicePipelineJobDescriptionLines -ServiceJob $serviceJob)
}

$document = $lines -join [Environment]::NewLine

Write-RepoDocument -RepoRoot $root -Path $OutputPath -Document $document -Description "Jenkins Job DSL"
